# Generated by Django 4.2.16 on 2025-03-29 14:28

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'خبرها'},
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
