# Generated by Django 4.2.16 on 2024-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='datetime_viewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
