# Generated by Django 5.2 on 2025-06-03 08:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
