# Generated by Django 5.2 on 2025-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('login', 'ورود به حساب کاربری'), ('logout', 'خروج از حساب کاربری'), ('profile_edit', 'ویرایش پروفایل'), ('post_create', 'ارسال پست جدید'), ('comment_create', 'ارسال دیدگاه'), ('post_edit', 'ویرایش پست '), ('post_delete', 'حذف پست '), ('news_create', 'ارسال خبر جدید'), ('news_edit', 'ویرایش خبر '), ('news_delete', 'حذف خبر '), ('settings_edit', 'ویرایش تنظیمات')], max_length=50),
        ),
    ]
