# Generated by Django 4.2.16 on 2025-04-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای سئو. حداکثر 160 کاراکتر.', max_length=160, null=True),
        ),
    ]
