# Generated by Django 4.2.16 on 2025-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای سئو. حداکثر 160 کاراکتر.', max_length=160, null=True),
        ),
    ]
