# Generated by Django 4.2.16 on 2025-04-08 10:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
