# Generated by Django 4.2.16 on 2025-04-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_meta_description'),
        ('blog', '0019_alter_post_text'),
    ]

    operations = [
    ]
