# Generated by Django 5.2 on 2025-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=50, verbose_name='نام سایت')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='متن فوتر')),
                ('about_text', models.TextField(blank=True, verbose_name='توضیحات سایت')),
                ('show_social_links', models.BooleanField(default=True, verbose_name='نمایش لینک\u200cهای اجتماعی در صفحه اصلی')),
                ('show_top_post', models.BooleanField(default=True, verbose_name='نمایش پست های برتر در صفحه اصلی')),
                ('show_random_post', models.BooleanField(default=True, verbose_name='نمایش رندوم پست ها')),
                ('show_recent_post', models.BooleanField(default=True, verbose_name='نمایش پست های اخیر')),
                ('show_tags', models.BooleanField(default=True, verbose_name='نمایش تگ ها')),
                ('show_categories', models.BooleanField(default=True, verbose_name='نمایش دسته بندی ها')),
                ('show_monthly_archive', models.BooleanField(default=True, verbose_name='نمایش آرشیو ماهانه')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شبکه اجتماعی')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='کلاس آیکون (اختیاری)')),
            ],
            options={
                'verbose_name': 'لینک اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای اجتماعی',
            },
        ),
    ]
