# Generated by Django 5.2 on 2025-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='توضیحات سئوی سایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title سایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_title_seo',
            field=models.CharField(blank=True, max_length=50, verbose_name='seo title'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
