# Generated by Django 5.2 on 2025-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesetting_site_description_sitesetting_site_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_about_text',
            field=models.BooleanField(default=True, verbose_name='نمایش درباره وبلاگ در صفحه اصلی'),
        ),
    ]
