# Generated by Django 5.2 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesetting_show_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='درباره وبلاگ'),
        ),
    ]
